[project]
name = "homework-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scikit-learn==1.6.1",
]
[tool.poetry.dependencies]
fastapi = "^0.101.1"
uvicorn = "^0.26.1"